name: Go

on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go mod download

    - name: Running tests
      run: go test -v .
    
    - name: Coverage
      env: 
        CODECOV_TOKEN: 69834835-9abf-42f6-bf32-bd93f878b9ca
      run: bash <(curl -s https://codecov.io/bash)
    
